# Generated by Django 3.0.1 on 2019-12-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_branzy', models.CharField(max_length=200)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branża',
                'verbose_name_plural': 'Branże',
            },
        ),
        migrations.CreateModel(
            name='TypSpotkania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_spotkania', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Typ spotkania',
                'verbose_name_plural': 'Typy spoktania',
            },
        ),
        migrations.CreateModel(
            name='Spotkanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('obecnosc', models.BooleanField(default=False)),
                ('typ_spotkania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlin.TypSpotkania')),
            ],
            options={
                'verbose_name': 'Spotkanie',
                'verbose_name_plural': 'Spotkania',
            },
        ),
        migrations.CreateModel(
            name='Specjalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('aktywna', models.BooleanField(default=True)),
                ('branza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlin.Branza')),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
            },
        ),
        migrations.CreateModel(
            name='Gosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('telefon_komorkowy', models.IntegerField()),
                ('telefon_stacjonarny', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('nazwa_firmy', models.CharField(max_length=200)),
                ('branza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlin.Branza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gość',
                'verbose_name_plural': 'Goście',
            },
        ),
    ]
