# Generated by Django 3.0 on 2019-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('telefon_komorkowy', models.IntegerField()),
                ('telefon_stacjonarny', models.IntegerField()),
                ('branza', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('nazwa_firmy', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Gosc',
                'verbose_name_plural': 'Gosci',
            },
        ),
    ]
