# Generated by Django 3.0.1 on 2019-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlin', '0002_auto_20191230_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gosc',
            name='telefon_komorkowy',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gosc',
            name='telefon_stacjonarny',
            field=models.CharField(max_length=20),
        ),
    ]
