# Generated by Django 3.0.1 on 2019-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlin', '0003_auto_20191230_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotkanie',
            name='obecnosc',
            field=models.BooleanField(default=False, verbose_name='obecność'),
        ),
    ]
